[package]
name = "bevy_dui"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.79"
bevy = { version = "0.17.3", default-features = false }
quick-xml = "0.31"
bevy_ecss = { path = "../bevy_ecss-fork" }

[dev-dependencies]
bevy = { version = "0.17.3", default-features = true }

# [patch."https://github.com/robtfm/bevy"]
# bevy = { path = "../bevy" }

# [patch."https://github.com/robtfm/bevy_ecss"]
# bevy_ecss = { path = "../bevy_ecss" }
